apiVersion: v1
kind: Pod
metadata:
  labels:
    team: dotnet
spec:
  containers:
  - name: jnlp
    image: hub.xueerqin.net/yunwei/jenkins-slave-dotnet:v7
    env:
    - name: "DOTNET_CLI_TELEMETRY_OPTOUT"
      value: "true"
    command:
    - jenkins-agent
    tty: true
    resources:
      requests:
        cpu: "1500m"
        memory: "1500Mi"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "volume-workspace"
      readOnly: false
    - mountPath: "/home/jenkins/deployment"
      name: "volume-deployment"
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/usr/bin/docker"
      name: "volume-1"
      readOnly: false
    - mountPath: "/usr/bin/kubectl"
      name: "volume-2"
      readOnly: false
    - mountPath: "/home/jenkins/nuget"
      name: "volume-nuget"
    workingDir: "/home/jenkins/agent"
  securityContext:
    runAsUser: 0
  volumes:
  - hostPath:
      path: "/data/jenkins-slave/dotnet"
    name: "volume-workspace"
  - hostPath:
      path: "/data/jenkins-slave/k8s-deploy/dotnet"
    name: "volume-deployment"
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"
  - hostPath:
      path: "/usr/bin/docker"
    name: "volume-1"
  - hostPath:
      path: "/usr/local/bin/kubectl"
    name: "volume-2"
  - hostPath:
      path: "/data/jenkins-slave/nuget"
    name: "volume-nuget"
  - emptyDir:
      medium: ""
    name: "workspace-volume"